NUMBER_CLUSTERS = 20
display_plots = False

AFFINITY_PROPAGATION_CONVERGENCE_ITERATIONS = 500
AFFINITY_PROPAGATION_MAX_ITERATIONS = 20000

OPTICS_MIN_SAMPLES = 5

K_MEANS_N_INIT = 10

BIRCH_BRANCHING_FACTOR = 50
BIRCH_THRESHOLD = 0.5

DBSCAN_EPS = 50
DBSCAN_MIN_SAMPLES = 3

# aco settings
ACO_ALPHA_VALUE = 1
ACO_BETA_VALUE = 10
ACO_RHO_VALUE = 0.03
ACO_Q_VALUE = 1
ACO_ANT_COUNT = 50
ACO_ITERATIONS = 500
