NUMBER_CLUSTERS = 20
display_plots = False

AFFINITY_PROPAGATION_CONVERGENCE_ITERATIONS = 500
AFFINITY_PROPAGATION_MAX_ITERATIONS = 20000

OPTICS_MIN_SAMPLES = 5

K_MEANS_N_INIT = 10

BIRCH_BRANCHING_FACTOR = 50
BIRCH_THRESHOLD = 0.5

DBSCAN_EPS = 20
DBSCAN_MIN_SAMPLES = 3
